spring:
  application:
    name: example

  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/regram?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        initialization-fail-timeout: -1
    slave1:
      jdbc-url: jdbc:mysql://localhost:3307/regram?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        initialization-fail-timeout: -1
    slave2:
      jdbc-url: jdbc:mysql://localhost:3308/regram?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    defer-datasource-initialization: false
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    # 트랜잭션 시작/커밋/롤백 로그
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    # LazyConnectionDataSourceProxy 실제 커넥션 획득 시점 로그
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG
    org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.pool.HikariPool: TRACE
    com.zaxxer.hikari.pool.PoolBase: TRACE
    org.hibernate.engine.jdbc.connections: DEBUG
    org.hibernate.resource.jdbc: DEBUG
    com.example.example: DEBUG